### ISSUE TITLE
Installing Luppp error

### ISSUE THREAD

**Issue by 4471** [openAVproductions/openAV-Luppp#108]
Hi. I am trying to install Luppp but I am getting this Error message:
Can't find ./waf directory (it doesn't exists). What should I do?

**Comment by harryhaaren** [comment]
Hi @4471 ,

Please see the build instructions here:
https://github.com/harryhaaren/openAV-Luppp/#install

That should work - Luppp no longer uses Waf. Where did you find instructions that ./waf should work? I'd like to update the docs if I can.

Thanks, -Harry

**Comment by gplocke** [comment]
He might be running into a similar issue that I am.  I'm very interested in trying to help with this project but I'm having some issues getting some of the prereqs installed on my Mac.  Specifically NTK.  The instructions say to git clone the git.tuxfamily.org/gitroot/non/fltk.git package and that library is compiled using waf.

From the ntk README:

     Building and installing generally goes like:

     ./waf configure
     ./waf
      su -c './waf install'

I had problems with getting this to build as it requires x11, and I can't for the life of me figure out how to get it to find the x11 libs...then I can't build Luppp cause it requires both ntk and x11.

**Comment by gplocke** [comment]
I managed to get a little further (I'm on OSX El Capitan).  I installed Xquartz (for X11) from https://www.xquartz.org and fltk, cairo, liblo, libsndfile, libsamplerate, and jack with Homebrew.

     brew install fltk cairo liblo libsndfile libsamplerate jack

But I had to manually set the PKG_CONFIG_PATH in order to get pkg-config to find the libs

     echo "export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib:/opt/X11/lib/pkgconfig" >> ~/.bashrc && source ~/.bashrc

Once I did that it got a little further, but ntk because various things aren't right with that it seems.  So I figured that it's really basically just fltk, so installing that should be ok.  The catch was there's no pkgconfig for fltk that I could find...and it wants ntk.  So I made an ntk.pc file for it in /usr/local/lib/pkgconfig

     #fltk (aka ntk)

     prefix=/usr/local/Cellar/fltk/1.3.3
     exec_prefix=${prefix}
     libdir=${exec_prefix}/lib
     includedir=${prefix}/include

I'm sure there are problems with all of this, but it at least got luppp to at least get past the compilation dependency check successfully.  Now I get type errors with cairo...I have version 1.14.6_1 currently installed.  Not sure what version it expects, but it's obviously not the right one...  Would love any advice on this, but this is definitely overly complex.

**Comment by gplocke** [comment]
One last thing I tried.  I downloaded the latest fltk from http://www.fltk.org/ instead and noticed that you can enable the cairo hooks with

     ./configure --enable-cairo

and that will generate a libfltk_cairo.a library, and I updated the ntk.pc file I had made to point to that instead but that still gives me a lot of errors like:

     openAV-Luppp-master/src/avtk/avtk_radial_status.h:93:9: error: unknown type name 'cairo_t'
        cairo_t *cr = Fl::cairo_cc();

So, I'm at a point where I'm not sure what else to try...

**Comment by harryhaaren** [comment]
Hi @gplocke!

Luppp now uses CMake, and you should probably try using that (see build instructions linked to above..)

Note that Luppp is developed and tested only on Linux. I'm not sure of the NTK on OsX status, so perhaps it is not currently possible to compile Luppp... that said - I just don't know, because I've never tried.

Thanks for reporting you progress here though - interesting to see :) -Harry

**Comment by gplocke** [comment]
Thanks @harryhaaren, I figured that was the case :-(  But I've got it close on OSX, I'm just missing that FLTK with Cairo hooks connection it would seem.  I did do the cmake .. and make steps and that's when I get the errors I mentioned above.

Maybe I'll play with this a little more to see if I can figure out how to get NTK to compile on OSX and try again.  That definitely seems like the missing piece of the puzzle here.  It's close I think though...I'm just getting some redefinition errors that are conflicting with things defined in X11.

But on the Non website they have a FAQ that says the following, so I don't know how much support I'm gonna find for getting it to build correctly on OSX.

**Why don't you provide OS X or Windows binaries?**

_Unlike, ahem, some other DAW projects, the direction of Non is not driven by financial interests. Time and money spent aquiring the special hardware and software to develop on closed platforms would, in my humble opinion, be better spent on actually developing Non._

Thanks for your reply!

**Comment by harryhaaren** [comment]
@gplocke, the NTK developer was very active in the community a few years ago - and has become less active over the years. If I recall correctly, NTK's Cairo subsystem is totally overhauled from FLTKs, and only implemented for X11. (Various parts have only XLib based backends: https://github.com/original-male/ntk/commit/3e198b441ce6efd8276913685de45027545b681d#diff-29cb951c85881e7cd3115a2d6f097a8eR125 )

Note that OpenAV software will be moving away from NTK, and towards AVTK (the OpenAV toolkit) because it is entirely statically linked, and has very few dependencies: http://openavproductions.com/code/avtk/

Cheers. I'll mark this issue as closed - which I should probably have done after https://github.com/openAVproductions/openAV-Luppp/issues/108#issuecomment-183405645

Cheers, and any questions just open a new issue :) -Harry
