### ISSUE TITLE
ReStyle Codebase

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Luppp#153]
This tracks the issue that the codebase is slowly becoming more messy, and some style issues are creeping in. To resolve this, after the 1.1 release, astyle will process the *entire codebase* and provide a consistent style.

From that point onwards, patches should be submitted using the new style. This can be achieved by
- Having the correct formatting (manually checked and coded that way)
- Having been formatted by `astyle` which will auto-format the source correctly :)

**Comment by georgkrause** [comment]
i expect that this will break the mergability of all pending prs, right? So it might be a good idea to merge before, to prevent any trouble. i am thinking about #144.

**Comment by harryhaaren** [comment]
Yes it will, and indeed I would like to include that PR, but I'm not home yet to be able to test it.

**Comment by harryhaaren** [comment]
@georgkrause I didn't merge the PR #144 above, its cleaner to have seperate commits. If you really don't want to do the rebase on master, I can do the porting of the functionality, but I don't have a device to test with.

**Comment by georgkrause** [comment]
@harryhaaren well i will do the rebase anyway because i need a part of the pr, so even if you wont merge i will have a working branch with this feature on my device ;) you can merge it or not, i understand why you dont want to without testing. you can at least try if there are any issues with your controllers and my patch... if not it should be okay to merge.

**Comment by harryhaaren** [comment]
@georgkrause cool; file a new PR and I'll test with the APC40 controller (I don't have it here now), and I'll merge then. Thanks!
