### ISSUE TITLE
Luppp translation

### ISSUE THREAD

**Issue by rcaneill** [openAVproductions/openAV-Luppp#166]
Hi,
I don't know how it is possible, but is it possible to do a translation of the interface? Is it easy to do now or is all the text directly implemeted inside the source code (I mean that if it is in the code, it seems complicated to maintain the different versions of languages, instead of having a kind of file that contains the translations).
if it is possible, I'll be happy to help for the french translation! (with help from someone to explain me the beginning of how doing that, and I can search by myself of course).
Romain

**Comment by trebmuh** [comment]
Interesting question. @harryhaaren you already now that I'm interested in software translation, don't you? I can help as well and we could team up with @rcaneill to provide an awesome French interface to the French readers (if/when such a possibility of translation is made within the code since I don't like too much to 'hardpatch' the sources).

**Comment by georgkrause** [comment]
@rcaneill Thank you for your question! At the moment all text is implemented in the source code. So it would be possible to fork and create a translated version of Luppp, but this would need a maintainer. It would also be possible to implement a translation system, this is some work. We can keep this as feature request, but from my point of view there isnt a lot of time in the near future for this.

Since the interface of Luppp does not have many text it might be better to spend some time on translating the docs. The code isnt published yet, but @harryhaaren wants to and if its done this might be a better way to have an easy start for french users?

**Comment by rcaneill** [comment]
Sure, translating the docs is a good thing to do! I'ld be happy to do it with @trebmuh

**Comment by trebmuh** [comment]
@georgkrause let us know when translating the doc will be available to do.

**Comment by georgkrause** [comment]
we should discuss anyway, if it makes sense to translate the interface. for me its pretty easy to understand what the elements of the interface do, but maybe someone else has problems?

**Comment by trebmuh** [comment]
Yes, any people not used to English (which is approximatively 5/6 of humanity).

**Comment by harryhaaren** [comment]
Hi All,

I see very little value in translating the Luppp interface itself - tutorials, documentation and demo videos would be much more helpful both for beginner users and helping show people Luppp exists.

On a technical note; translating the application is not easily possible, and would require developer effort - another reason I see it as not worth doing; there are more important things to be done.

Manual is available at this repo, please continue any discussion about translations here:
https://github.com/openAVproductions/manual/issues/1

Please think about if translation is really the best way forward - see this:
https://github.com/openAVproductions/manual/issues/2

So my preference is as follows:
1: Video tutorials / demos
2: Documentation translations
... (don't know yet) ...
9: Translate the Luppp UI.

Closing this issue, as we should discuss translation/video at the above links.

**Comment by georgkrause** [comment]
i dont think the discussion is over here, obviosly there can be a need for translated interface. 

but, @trebmuh i know many people dont speek english, but look at the interface, there are only a few words. and these are something like "Master". The principle here is that the user knows which button has which functionallity since one word wouldnt discribe the most of them in a adequate way...

**Comment by trebmuh** [comment]
hey @georgkrause : while I can understand that people with basic English skills like you, your friend, myself and some of my friend, what about people even not using Latin characters? Or people not using letter but picture? Or culture reading from right to left? This is where translatibility (yes, the word doesn't exist :) ) is showing its powerfulness when one want to share a software/knowledge/literature ...

**Comment by georgkrause** [comment]
Well i understand the importance of translations in generel, and i see your point. but in the luppp interface there are almost no words. Except the menu. 
All in all its a pretty simple formula. we dont have unlimited dev time. so we need to think about how we invest it. the question is now: is a translated documentation enough to use luppp in english? i cannot decide it, since i know english pretty well and dont have problems. 

At the and we can reopen this issue and leave it, until someone does it. this shouldnt hurt. Also, i can do some research on doing translation right, maybe it isnt that much work as i think at the moment.
