### ISSUE TITLE
Stereo FX

### ISSUE THREAD

**Issue by nanu-c** [openAVproductions/openAV-Luppp#169]
Today I came on the idea to use a rotating flanger and by using the the fx every stereo-Effect is gone.

Are the tracks completely mono? Could it be stereo?

**Comment by harryhaaren** [comment]
Thanks for the feature-request!

It is possible to use the JACK FX Send to split to stereo, but an external mixer would have to be used (since Luppp's internal mixer is mono only at the moment).

It is possible to convert A) all of luppp, or B) just the post-JACK-FX return to stereo. It would need developer time and to be prioritized above other things. I unfortunatly don't have much time to work on new features at the moment, sorry.

**Comment by nanu-c** [comment]
It's working!

**Comment by harryhaaren** [comment]
@nanu-c yep, shout out to @coderkun for implementing it! If you have any issues with the latest git code, please say so now (https://github.com/openAVproductions/openAV-Luppp/issues/179) as I would like to release 1.1.1 this week. Thanks, -H
