### ISSUE TITLE
Will there come a new version of Luppp?

### ISSUE THREAD

**Issue by ArneSchulz** [openAVproductions/openAV-Luppp#192]

**Comment by harryhaaren** [comment]
Hi Arne,

Currently I don't have patches / features that I'm waiting to merge or so. Do you see much value in releasing with the few commits that have been integrated since then? [see here for commit log](https://github.com/openAVproductions/openAV-Luppp/commits/master). Is there something currently outstanding that you're waiting for?

**Comment by georgkrause** [comment]
In my opinion there is not that much new stuff worth releasing, the main new "feature" (clear clips with midi) isn't ready til now. 

Thinks are moving pretty slow, but they are moving. We should release unready stuff just for doing it but test intensive and provide a version of luppp which has a consistent state.

**Comment by harryhaaren** [comment]
Yes there will be new versions of Luppp. Cleaning up bug-tracker so closing

**Comment by georgkrause** [comment]
only to correct myself: of course we SHOULD NOT release unready stuff ;) sorry for this error
