### ISSUE TITLE
NanoKontrol2 not mapping properly.

### ISSUE THREAD

**Issue by Skrappjaw** [openAVproductions/openAV-Luppp#193]
As the title says. The controller does not map at all. Using kxstudio repos on KDE neon. Jack with carla and cadence.

**Comment by harryhaaren** [comment]
Hi @Skrappjaw!

Thanks for reporting an issue. In order to help you, I'll need to understand what you're doing, and what you're expecting to happen too. If you're not familiar with MIDI bindings in Luppp yet, the following video tutorial might help: https://www.youtube.com/watch?v=kOGh2tsXBcA

Cheers, -Harry

**Comment by georgkrause** [comment]
@Skrappjaw If you need some personal help making the NanoKontrol working, i could assist you. Let me know. If i get such an device in my handy i could also provide an controller map for it. but chances are low at the moment :(

**Comment by georgkrause** [comment]
Since here is no more information about, i close it.

@Skrappjaw feel free to answer or reopen if you have some information.
