### ISSUE TITLE
lv2 plugin version

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#234]
@han-so1omon wants to have a lv2-plugin version of luppp.

I am quite sceptic, but lets discuss this ;)

**Comment by han-so1omon** [comment]
I really want to use a looper with Ingen. The first thing to consider is resource management, so that plugin GUI uses very few resources. It should be able to be loaded multiple times. It should loop very simple and take up a minimal amount of screen space. Other than that I think it will be very similar to existing Luppp.

**Comment by harryhaaren** [comment]
@han-so1omon, have you looked at the existing LV2 loopers? A number of them are available - none are fully featured, with mutli-clip and scenes etc, however basic looping is covered by them. What would need to change to make one of those loopers suffice for your workflow?

The back-story here is that Luppp is not an LV2 plugin, and was not designed to be an LV2 plugin. "In theory" it could be - however it would require a major refactor, and I don't see that as "going to happen in practice".

I do hope to work on sequencer/looper style plugins for LV2, however they will not be Luppp, but separate smaller projects.

Hope that makes sense, -Harry

**Comment by georgkrause** [comment]
@harryhaaren I would expect this to be a no-fix. So I suggest to close this issue.
