### ISSUE TITLE
No way to remove effects

### ISSUE THREAD

**Issue by Upacesky** [openAVproductions/openAV-Luppp#29]
After adding any kind of effect on a track, I just can't remove them.

**Comment by baptx** [comment]
@harryhaaren I saw this issue was closed, is it fixed? I did not find a way to remove a recording in the latest stable release.

**Comment by harryhaaren** [comment]
Hi @baptx, I think this issue was filed against a previous version of the codebase. The current version of Luppp does not support any internal effects.

Your question seems to be related to removing a "recording", not an effect?
If so, right-click on the recording itself, and the "Clear" menu item (at the bottom) will remove it.

**Comment by baptx** [comment]
Hi @harryhaaren, yes I meant the recording, I missed the right click, thanks. It would be nice if we can remove a recording with the keyboard only by pressing the "Delete" key. It would be more natural since we can already use the keyboard to start / stop a recording. Should I create a new issue for that?

**Comment by harryhaaren** [comment]
Yes, open a new issue please.
