### ISSUE TITLE
It's not possible to set Jack Transport back to start.

### ISSUE THREAD

**Issue by grammoboy2** [openAVproductions/openAV-Luppp#302]
It's not possible to set Jack Transport back to start. Luppp runs from The Netherlands to Ireland if you don't stop it. No way to get is back to start (monopoly trauma? ;) )

This way I can't play with non-timeline doing automation in non-mixer, which is processing audio from Luppp.

**Comment by moonshaadow** [comment]
Same here.
Related to #280 I think.
The way luppp manages transport seems buggy. It makes luppp unusable with other apps, and it's a shame. Sync and transport should be a main feature for a looper. By the way I think ableton link is _another_ step. Transport has to be fixed first.
Is the same problem in NSM ? I'm gonna take a look.

**Comment by moonshaadow** [comment]
Same in NSM.

**Comment by harryhaaren** [comment]
JACK Transport bugs are a known issue - already being tracked here: https://github.com/openAVproductions/openAV-Luppp/issues/280.

Note that NSM being in use or not will have no effect at all on how JACK Transport/Timebase is handled.

Note also that the JACK Transport isn't natively a good match for live looping, due to "Slow Start" clients and such. Technically Ableton's Link is a closer match for what Luppp would like to achieve - being in sync (beat and phrase) with other applications.. which is already filed as a different feature-request here: https://github.com/openAVproductions/openAV-Luppp/issues/303

I'll close this to avoid too many tracks on the same topic - thanks for raising concerns though. Further discussion on each topic in the relevant issue please :) Cheers, -Harry
