### ISSUE TITLE
Disable sync'ed start

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Luppp#67]
Email from the LAD mailing list, discussion continued here:

```
Hey !

I've toyed a bit with loop, it's great and all, but -except if I missed the feature-
I haven't found any ways to disable sync'ed record and, more importantly, sync'ed play.

I'd like to be free to record any length of loops, and play them in a non-quantized manner.
Just a midi mappable button would do the trick.

Also, is it possible to launch an individual loop ? or must I play an entire row every time?
If not, that'd be a nice feature.

Cheers, that's a nice piece of software !

keep up with good work !

E.:.T
```

**Comment by georgkrause** [comment]
I worked on the overview on Luppps tempo feature requests (#138) and found this one. There is already another issue for other tempo signatures than 4/4: #126 

The feature request here was to disable sync, the reaction of @harryhaaren sounds like a wontfix because it does not fit in the concept of luppp. but this topic is about 3 years old, how is the current state of the discussion?

**Comment by georgkrause** [comment]
@harryhaaren any updates on this?

**Comment by harryhaaren** [comment]
I have no objections at all to adding other time signatures - but the user-experience must not get more complicated. Keep in mind this is difficult work to test - so this should not be taken on easily.

I do not think that I will be working on adding other time-signatures, but a properly formatted PR will be merged. I don't think this should be commited for a particular release because the work hasn't even been started yet.

**Comment by georgkrause** [comment]
@harryhaaren if the topic of this issue is only to add other time signatures, we can close this because there is another issue with the same topic: #126 
I wanted to know if the possibility to disable the sync is a wont fix, in this case we can close this. If not, i think its related to the rework of the tempo manager. This is something Gerald wants to work on in January and this is why i planned this for 1.3

**Comment by harryhaaren** [comment]
Ok done, closing this.
