### ISSUE TITLE
Metronome Samples

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Luppp#88]
From this original issue, moved to here for coherence:
'''Also an idea, maybe be able to change the actual metronome sound via sample .wav file?'''

**Comment by harryhaaren** [comment]
Just a note that the @geraldmwangi 's great work has updated the metronome samples, and his pull-request ( https://github.com/openAVproductions/openAV-Luppp/pull/109 ) has been merged.

**Comment by georgkrause** [comment]
+1 here ;)

**Comment by harryhaaren** [comment]
@georgkrause : what priority do you rate this? Personally I'd say low (so it won't get done any time soon...) , but curious what others think.

**Comment by georgkrause** [comment]
@harryhaaren need to use hard words now, sorry ;) since the current sound of the metronome is hardly annoying its nearly impossible to record something in a relaxed way to the click. at the moment i record my own metronome at the beginning watching the colored bar in the right buttom. since i think a change would be much work it would be the first i would do ;) but: luppp is working without this change so its not critical ;)

**Comment by georgkrause** [comment]
@harryhaaren would be enough for me if the volume can be set. i see there is the code for, but the gui control is missing?

**Comment by harryhaaren** [comment]
Right click the metronome dial - bingo :smile:

**Comment by georgkrause** [comment]
great, so for me its done ;)

**Comment by harryhaaren** [comment]
Cool cool, closing because I don't see any work here happening in the near future. Cheers
