### ISSUE TITLE
losing sync between loops during session

### ISSUE THREAD

**Issue by genesis66** [openAVproductions/openAV-Luppp#93]
Hi, I have setup luppp with non-mixer+jack+lmms-vst with external controler apc mini. Everything is working almost fine.....except that I "randomly" loose sync between loops when recording live pattern (singing or playing synth).
When I launch luppp with the metronome, I set the tempo to the desired value, then load a few existing samples (drums, fx etc), then starts recording playnig rhodes or piano and singing, after one or 2 minutes, the lopps are totally "un-synced" with the tempo, and so un-synced at all one with the other.
It's a real shame because this is just unusable right now. my luppp.prfs is set to 2 (sync best), and even then it's the same problem.
Thanks for your help

**Comment by mrmowgli** [comment]
I'm using the latest version in KXStudio (They should package a newer version, if there's one stable enough) and definitely run into the sync issue.  I also get this:

```bash
$ luppp
[Luppp] main:61: Git: 
[Luppp] Gui:339: Gui()
[Luppp] Gui:444: Loaded preferences
[Luppp] Gui:470: No session management in use
[Luppp] Jack:90: Samplerate 48000
event
event
event
event
[ DSP ] :0: Timing Error: negative samples 128
[ DSP ] :0: Timing Error: negative samples 128
```


I get a lot of these negative sample messages, eventually with snaps and pops, and then worse sync issues.  Definitely would love to be able to stop and restart the loops without having to close Luppp.  Or at least force a restart  (With spacebar maybe?)

**Comment by harryhaaren** [comment]
Hi @mrmowgli, thanks for your comment. Using a "Scene Launch" command (can be MIDI bound, or '9','o','l','.' IIRC), will bring all loops back into sync.

I'm aware that the issue is a big one - unfortunately the fix is not obvious. I hope to release a new version of ArtyFX soon, and then finish this bug, along with some other cleanups. Cheers, -Harry

**Comment by geraldmwangi** [comment]
Hi Harry, I've testing Luppp
I came upon the same issue when live-sampling my bass guitar.
Jack is set samplerate 44100Hz, realtime.
What I did:
a) loaded luppp with the default tempo of 120bpm
b) triggered track 1 on scene 1 for record
c) Recorded 2 Bars (1Bar=4 beats on the metronom)
d) let the clip loop
e) after 8 bars the clip is audibally 180° out of phase
f) I have a good feel for tempo, so listening to the metronom alone I think the metronom is stable
g) Thus the clip length must be shorter or the clip is played faster at the same pitch
h) got the git code and looked at looper.cxx, I found the variable playSpeed in process()
i) printf playSpeed reveals playSpeed=1.018 and NOT =1.0 (I did not change the bpm! Still at 120bpm)
j) commenting out playSpeed=(float)actualFrames/targetFrames, thus leaving playSpeed=1.0 (the default) and compiling -> luppp stays perfectly in sync, not matter how many clips are played
k) this fixes however the clips to the bpm at which they where recorded, so bpm knob changes metronom but not the clip-speed.
l) didn't do the numbers but actualFrames { as computed from samplerate (round number), bpm (round) and nr of bar (even number )} and targetFrames  must also be  round numbers
m) printf'ing actualFrames and targetFrames, actualFrames is round while targetFrames is NOT round (thus they aren't equal)-> there is something wrong in the computation of targetFrames
n) for now I'm leaving playSpeed=1.0 since I don't depend on changing the bpm while looping

Hope this helps,
Gerald / JimsonDrift

**Comment by y1ds** [comment]
I was having the same issue. Changing  the line playSpeed=(float)actualFrames/targetFrames to playSpeed=(float)actualFrames/(float)targetFrames seems to be keeping sync at least a lot better.

**Comment by harryhaaren** [comment]
Hi @y1ds,

Gerald / JimsonDrift  has been doing awesome work and sending pull-requests[see below] - I think this issue is now resolved - @geraldmwangi am I right in says so?

Cheers, -Harry

[1] https://github.com/openAVproductions/openAV-Luppp/pull/111
[2] https://github.com/openAVproductions/openAV-Luppp/pull/110
[3] https://github.com/openAVproductions/openAV-Luppp/pull/109

**Comment by geraldmwangi** [comment]
Yes the issue is resolved. Loops stay in sync now since playSpeed has correct value now.
